### ISSUE TITLE
Please update revpop-core/programs/README.md

### ISSUE THREAD

**Issue by TropikalMonkey** [Revolution-Populi/revpop-core#13]
On https://github.com/Revolution-Populi/revpop-core/tree/master/programs#revpop-programs there are still references to "bitshares" and a link to "Delayed node" which was removed on commit: 2131f3a2924dfebfa4780a92ed0668d88ce2eb3a

**Comment by tedthecreator** [comment]
Hi @TropikalMonkey !
Thanks for your comment! We are currently doing a lot of research now and do not have time to update all the documentation although this task is in the plans.
I see you have prepared a request with changes https://github.com/TropikalMonkey/revpop-core/commit/134d97500bc33524c03b919bfed9ca7345c0f03a but sent it to your fork of the project.
Could you please send your request here too? Thank you!

**Comment by tedthecreator** [comment]
Thx, done.
