### ISSUE TITLE
Witness block generation issue, seeing "broadcast_commit" and "broadcast_reveal" but not generating

### ISSUE THREAD

**Issue by Fire-Gargoyle** [Revolution-Populi/revpop-core#26]
I know that this is something on my side that I probably messed up, but I figured I would reach out for help.  I followed the instructions to become a witness on the testnet here https://github.com/Revolution-Populi/revpop-core/wiki/How-to-become-a-witness-(Block-Producer) (which were very well written by the way!) but alas I am facing some issues.  When I get to the point to where I start up my witness node, which is setup with my witness-id and private-key pair, instead of seeing a message like:

"Witness 1.6.10 production slot has arrived; generating a block now...
Generated block #367 with timestamp 2021-06-08T20:46:30 at time 2021-06-08T20:46:30"

I am seeing blocks confirmed by other witnesses and two other messages similar to the below (minus some hashes and my account name):

"witness.cpp:489 broadcast_commit  Commit operation for the current maintenance period has already been made"

and then:

"witness.cpp:612 broadcast_reveal Double reveal operations is prohibited" (I only saw this message once)

I have confirmed that my account is upgraded to a "Lifetime Member" and also upgraded to a Witness on my account dashboard (https://testnet.revolutionpopuli.com/account/fire-gargoyle).  I see many events after that whose block numbers match up with the block numbers in the broadcast_commit messages.

I tried to vote again to check and make sure that it went through and the wallet confirmed for me that I had already voted for myself.  I also tried recreating the witness but the wallet confirmed for me that I was already a witness.  Yet when I check the get_global_properties I am not on the active witness list, even after the next maintenance period which I see with get_dynamic_global_properties.  However when I start my witness node I do see a line that states "Launching block production for 1 witnesses" in the witness plugin startup function and then "Plugin witness started".

Did I bork it?  Can I provide more information?  Maybe I just need more votes? *laugh* Thank you for any assistance.

**Comment by Fire-Gargoyle** [comment]
Ahh, okay I think I am connecting the dots.  It sounds like I am setup just fine but my witness node has simply not been chosen randomly yet as a lucky 21 active witnesses out of the top 63?  I see it shows as fire-gargoyle as a "Backup" right now and not "Active" in the voting tab on the testnet GUI.  Fire-gargoyle is in the top 63 so now I believe the node is just waiting to be picked?  Thank you for any clarification while I venture into this project.

**Comment by bhtechno** [comment]
Give us an update if you manage to start producing blocks. I had the same assumption that I have a 33.3% chance each hour to get selected, but after several hours wasn't selected at all. I'm wondering if there's a misunderstanding of how the selection process happens, or there's an issue with the node setup.

**Comment by Fire-Gargoyle** [comment]
> Give us an update if you manage to start producing blocks. I had the same assumption that I have a 33.3% chance each hour to get selected, but after several hours wasn't selected at all. I'm wondering if there's a misunderstanding of how the selection process happens, or there's an issue with the node setup.

BOOM!  We are golden!!!  Case closed!  I had run the node yesterday for a couple hours to no avail but today after only about 3 hours it looks like fire-gargoyle is good to go!  Hang in there! [https://i.imgur.com/Ei3KDXt.png](url)
